services:
  redis:
    image: "redis:alpine"
    container_name: cache-redis
    restart: on-failure
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis-data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - cache_network

  typesense:
    image: typesense/typesense:26.0
    container_name: cache-typesense
    restart: on-failure
    ports: 
      - "8108:8108"
    volumes:
      - ./typesense/dbdata:/data
    command: >
      --data-dir /data --api-key=${TYPESENSE_API_KEY} --enable-cors
    networks:
      - cache_network

  typesense-dashboard:
    image: bfritscher/typesense-dashboard:1.9.1
    container_name: cache-typesense-dashboard
    restart: on-failure
    ports:
      - "80:80"
    depends_on:
      - typesense
    networks:
      - cache_network

networks:
  cache_network:
    name: cache_network
